baseURL: "https://bearsdownstairs.com/"
theme: "up-business-bear-theme"
languageCode: "en-us"

title: "Bears Downstairs"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Bears Downstairs"
  description: "A group of bears making games."
  # images: 
  #   - "images/bears-downstairs.jpg"

  # logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # dribbble: "#"
    # instagram: "#"
    # facebook: "#"
    twitter: "https://twitter.com/BearsDownstairz"

  location:
    - "Metro Manila, Philippines"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "info.bearsdownstairs@gmail.com"
  #   - "207.555.0119"

  copyright: "Â© 2022 Bears Downstairs All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    - name: "Our Team"
      url: "/team"
      weight: 3

    - name: "Our Works"
      url: "/portfolio"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    - name: "Our Team"
      url: "/team"
      weight: 3

    - name: "Our Works"
      url: "/portfolio"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
